new-resource:
  - '(new-resource|[Nn]ew [Rr]esource)|[Aa]dd [Nn]ew [Rr]esource)'

resource:
  - '(current-resource|[Cc]urrent [Rr]esource|existing resource)'

new-data-source:
  - '(new-data-source|[Nn]ew [Dd]ata [Ss]ource)|[Aa]dd [Nn]ew [Dd]ata [Ss]ource)'