dependencies:
  - '.github/dependabot.yml'

documentation:
  - '**/*.md'
  - 'docs/**/*'
  - 'templates/**/*'

examples:
  - 'examples/**/*'

github_actions:
  - '.github/*.yml'
  - '.github/workflows/*.yml'

linter:
  - 'scripts/*'
  - '.github/workflows/terraform-provider-check.yml'
  - '.github/workflows/workflow-lint.yml'

provider:
  - '.gitignore'
  - '*.md'
  - 'internal/provider/**/*'
  - 'main.go'

repository:
  - '.github/**/*'
  - 'GNUmakefile'
  - 'infra'

tests:
  - '**/*_test.go'

