name: Feature Request
description: Something is missing or could be improved.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this feature request! Please note that this issue tracker is only used for bug reports and feature requests. Other issues will be closed.

        If you have a configuration, workflow, or other question, please go back to the issue chooser and select one of the question links.
  - type: textarea
    id: versions
    attributes:
      label: Terraform CLI and Provider Versions
      description: What versions of Terraform CLI and the provider?
      placeholder: Output of `terraform version` from configuration directory
    validations:
      required: true
  - type: textarea
    id: affected-resource-name
    attributes:
      label: Affected Resource(s)
      description: What resource(s) are affected?
      value: |
      "- atlassian_xxx"
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Cases or Problem Statement
      description: What use cases or problems are you trying to solve?
      placeholder: Description of use cases or problems.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What solutions would you prefer?
      placeholder: "```hcl\n resource \"atlassian_xxx\" \"this\" {\n    ...\n}\n```"
    validations:
      required: true
  - type: dropdown
    id: impact
    attributes:
      label: How much impact is this issue causing?
      description: "- High: represents completely not able to use the provider without this.\n- Medium: represents unable to solve a specific problem or understand something.\n- Low: represents minor provider code, configuration, or documentation issues."
      options:
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Are there any additional details about your environment, workflow, or recent changes that might be relevant? Have you discovered a workaround? Are there links to other related issues?
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow HashiCorp's [Community Guidelines](https://www.hashicorp.com/community-guidelines).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
