//go:build ignore

package main

// package prlabels

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"os"
	"regexp"
	"sort"
	"strings"
	"text/template"
	"time"
)

const (
	filename = `../../../.github/labeler-pr-labels.yml`
)

type Label struct {
	LowerCasePlural        string
	WithUnderscoreSingular string
}

type templateData struct {
	Labels []Label
}

func main() {
	fmt.Printf("Generating %s\n", strings.TrimPrefix(filename, "../../../"))

	productUrls := []string{
		"https://developer.atlassian.com/cloud/jira/platform/swagger-v3.v3.json",
	}

	lbs := []Label{}

	for _, v := range productUrls {
		lbs = append(lbs, getLabels(v)...)
	}

	td := templateData{}
	td.Labels = append(td.Labels, lbs...)

	sort.SliceStable(td.Labels, func(i, j int) bool {
		return td.Labels[i].LowerCasePlural < td.Labels[j].LowerCasePlural
	})

	writeTemplate(tmpl, "prlabeler", td)
}

func getLabels(url string) []Label {
	c := http.Client{Timeout: time.Duration(2) * time.Second}
	resp, getErr := c.Get(url)
	if getErr != nil {
		log.Fatalf("error calling url (%s): %s", url, getErr)
		return nil
	}

	defer resp.Body.Close()

	body, readErr := ioutil.ReadAll(resp.Body)
	if readErr != nil {
		log.Fatalf("error reading response body %s", readErr)
	}

	var result map[string]interface{}
	parseErr := json.Unmarshal(body, &result)
	if parseErr != nil {
		log.Fatalf("error unmarshalling JSON response %s", parseErr)
		return nil
	}
	resp.Body.Close()

	r := regexp.MustCompile(`\(apps\)`)
	r2 := regexp.MustCompile(`jira|confluence`)
	productName := r2.FindString(url)
	var tags = result["tags"].([]interface{})
	var labels []Label
	for _, value := range tags {
		// Each value is an interface{} type, that is type asserted as map[string]interface{}
		// due to nested objects in the original JSON response
		m := value.(map[string]interface{})
		rawLabel := m["name"]
		ok := r.MatchString(rawLabel.(string))
		if ok {
			continue
		}
		l := singularizeLabelSuffix(productName, rawLabel.(string))
		labels = append(labels, l)
	}

	return labels
}

func writeTemplate(body string, templateName string, td templateData) {
	// If the file doesn't exist, create it, or append to the file
	f, err := os.OpenFile(filename, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		log.Fatalf("error opening file (%s): %s", filename, err)
	}

	tp, err := template.New(templateName).Parse(body)
	if err != nil {
		log.Fatalf("error parsing template: %s", err)
	}

	var buffer bytes.Buffer
	err = tp.Execute(&buffer, td)
	if err != nil {
		log.Fatalf("error executing template: %s", err)
	}

	if _, err := f.Write(buffer.Bytes()); err != nil {
		f.Close()
		log.Fatalf("error writing to file (%s): %s", filename, err)
	}

	if err := f.Close(); err != nil {
		log.Fatalf("error closing file (%s): %s", filename, err)
	}
}

func singularizeLabelSuffix(product, input string) Label {
	l := Label{}

	ies := regexp.MustCompile(`.*ies$`)
	s := regexp.MustCompile(`.*[^aeiou]s$|.*[^s]es$`)
	ses := regexp.MustCompile(`.*ses$`)

	b1 := ies.MatchString(input)
	b2 := s.MatchString(input)
	b3 := ses.MatchString(input)
	r := strings.NewReplacer(" ", "", "-", "")
	//r2 := strings.NewReplacer(" ", "_", "-", "_")
	l.LowerCasePlural = product + "/" + strings.ToLower(r.Replace(input))
	if b1 {
		l.WithUnderscoreSingular = product + "/" + strings.TrimSuffix(strings.ToLower(strings.ReplaceAll(input, " ", "_")), "ies") + "y"
	} else if b2 {
		l.WithUnderscoreSingular = product + "/" + strings.TrimSuffix(strings.ToLower(strings.ReplaceAll(input, " ", "_")), "s")
	} else if b3 {
		l.WithUnderscoreSingular = product + "/" + strings.TrimSuffix(strings.ToLower(strings.ReplaceAll(input, " ", "_")), "es")
	} else {
		l.WithUnderscoreSingular = product + "/" + strings.ToLower(strings.ReplaceAll(input, " ", "_"))
	}

	return l
}

var tmpl = `# YAML generated by internal/generate/prlabels/main.go; DO NOT EDIT.
dependencies:
  - '.github/dependabot.yml'
documentation:
  - '**/*.md'
  - 'docs/**/*'
  - 'templates/**/*'
examples:
  - 'examples/**/*'
github_actions:
  - '.github/*.yml'
  - '.github/workflows/*.yml'
linter:
  - 'scripts/*'
  - '.github/workflows/terraform-provider-check.yml'
  - '.github/workflows/workflow-lint.yml'
provider:
  - '.gitignore'
  - '*.md'
  - 'internal/provider/**/*'
  - 'main.go'
repository:
  - '.github/**/*'
  - 'GNUmakefile'
  - 'infra'
tests:
  - '**/*_test.go'
{{- range .Labels }}
{{ .LowerCasePlural }}:
  - 'internal/provider/*{{ .WithUnderscoreSingular }}.go'
  - 'internal/provider/*{{ .WithUnderscoreSingular }}_test.go'
{{- end }}
`
